CREATE DATABASE store_management;

CREATE  TABLE store(
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
address VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE supplier(
id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
phone VARCHAR(255) NOT NULL ,
email VARCHAR(255) NOT NULL UNIQUE,
brief_data TEXT,
PRIMARY KEY(id)

);
CREATE TABLE product(
 id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 name VARCHAR(255) NOT NULL,
 code INTEGER UNIQUE  NOT NULL,
 description TEXT,
 price DECIMAL(10,2) NOT NULL,
 PRIMARY KEY(id)

)
